Update CD.yml

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -134,21 +134,21 @@ jobs:
           fi
           echo "iam_role_arn=$IAM_ROLE_ARN" >> $GITHUB_OUTPUT
 
-      - name: Annotate ServiceAccount for EBS CSI Driver (IRSA)
-        run: |
-          set -euo pipefail
-          IAM_ROLE_ARN="${{ steps.tf.outputs.iam_role_arn }}"
-          if [ -z "${IAM_ROLE_ARN:-}" ] || [ "${IAM_ROLE_ARN}" = "null" ]; then
-            echo "IAM_ROLE_ARN is empty. Aborting."
-            exit 1
-          fi
+      # - name: Annotate ServiceAccount for EBS CSI Driver (IRSA)
+      #   run: |
+      #     set -euo pipefail
+      #     IAM_ROLE_ARN="${{ steps.tf.outputs.iam_role_arn }}"
+      #     if [ -z "${IAM_ROLE_ARN:-}" ] || [ "${IAM_ROLE_ARN}" = "null" ]; then
+      #       echo "IAM_ROLE_ARN is empty. Aborting."
+      #       exit 1
+      #     fi
 
-          echo "Annotating kube-system/ebs-csi-controller-sa with ${IAM_ROLE_ARN}"
-          kubectl -n kube-system annotate sa ebs-csi-controller-sa \
-            eks.amazonaws.com/role-arn="${IAM_ROLE_ARN}" --overwrite
+      #     echo "Annotating kube-system/ebs-csi-controller-sa with ${IAM_ROLE_ARN}"
+      #     kubectl -n kube-system annotate sa ebs-csi-controller-sa \
+      #       eks.amazonaws.com/role-arn="${IAM_ROLE_ARN}" --overwrite
 
-          echo "Restarting CSI driver pods to pick up the new IAM role..."
-          kubectl delete pod -n kube-system -l app.kubernetes.io/name=aws-ebs-csi-driver
+      #     echo "Restarting CSI driver pods to pick up the new IAM role..."
+      #     kubectl delete pod -n kube-system -l app.kubernetes.io/name=aws-ebs-csi-driver
      
 
       - name: Create external-secrets namespace
